"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

format = """
[░▒▓](green)\
$os\
$username\
[ ](green)\
$directory\
$character\
"""
right_format = """$git_branch $git_status $git_commit $all $cmd_duration"""

[username]
show_always = true
format = '[$user ](bg:green)'
disabled = false

[os]
disabled = false
style = 'bg:green'

[os.symbols]
Arch = "  "
Artix = "  "
CachyOS = "  "
Linux = "  "
Unknown = "  "

[cmd_duration]
format = "[$duration]($style)"

[directory]
format = "[$path]($style)"
truncation_length = 2
truncation_symbol = "…/"

[character]
success_symbol = "[](bold blue)"
error_symbol = "[✗](bold red)"
disabled = false

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "

[git_branch]
symbol = "  "
format = '[$symbol $branch (:$remote_branch)]($style)'

[git_status]
style = "bold blue"
format = "[$modified$deleted$untracked$ahead_behind]($style) "
modified = " "
deleted = " "
untracked = " "
ahead = " "
behind = " "
up_to_date = " "

[git_commit]
tag_symbol = '  '
format = '[$symbol($version)]($style)'

[conda]
symbol = "  "
format = '[$symbol($version)]($style)'

[dart]
symbol = "  "
format = '[$symbol($version)]($style)'

[docker_context]
symbol = "  "
format = '[$symbol($version)]($style)'

[hostname]
ssh_symbol = "  "
format = '[$symbol($version)]($style)'

[java]
symbol = "  "
format = '[$symbol($version)]($style)'

[kotlin]
symbol = "  "
format = '[$symbol($version)]($style)'

[lua]
symbol = "  "
format = '[$symbol($version)]($style)'

[nodejs]
symbol = "  "
format = '[$symbol($version)]($style)'

[package]
symbol = " 󰏗 "
format = '[$symbol($version)]($style)'

[php]
symbol = "  "
format = '[$symbol($version)]($style)'

[python]
symbol = "  "
format = '[$symbol($version)($virtualenv)]($style)'

[rust]
symbol = " 󱘗 "
format = '[$symbol($version)]($style)'

[gradle]
symbol = "  "
format = '[$symbol($version)]($style)'
